import { Injectable } from '@angular/core';
import {environment} from "../../../environments/environment";
/**
 * @author Buddhima Aushan
 * @version 1.0.0
 * @since 2024-12-10
 */
@Injectable({
  providedIn: 'root'
})
export class HttpService {

  constructor() { }

  // Common
  static SERVICE_PATH = environment.API_BASE_URL;

  //Auth Service
  static AUTH_USER_LOGIN = environment.AUTH_SERVICE.AUTH.USER_LOGIN;
  static AUTH_USER_ME = environment.AUTH_SERVICE.AUTH.USER_ME;
  static AUTH_ADD_ROLE= environment.AUTH_SERVICE.ROLE.ADD_ROLE;
  static AUTH_GET_ALL_ROLES= environment.AUTH_SERVICE.ROLE.GET_ALL_ROLES;
  static AUTH_GET_ROLE_BY_ID= environment.AUTH_SERVICE.ROLE.GET_ROLE_BY_ID;
  static AUTH_DELETE_ROLE_BY_ID= environment.AUTH_SERVICE.ROLE.DELETE_ROLE_BY_ID;
  static AUTH_USER_LOGOUT = environment.AUTH_SERVICE.AUTH.USER_LOGOUT;
  static GET_ROLE_NAMES = environment.AUTH_SERVICE.ROLE.GET_ALL_ROLE_NAMES;
  static GET_PAGE_NAMES = environment.AUTH_SERVICE.ROLE.GET_ALL_PAGE_NAMES;
  static GET_ALL_PRIVILEGES = environment.AUTH_SERVICE.ROLE.GET_ALL_PRIVILEGES;
  static UPDATE_PRIVILEGE = environment.AUTH_SERVICE.ROLE.UPDATE_PRIVILEGE;
  static GET_SECTION_NAMES = environment.AUTH_SERVICE.ROLE.GET_SECTION_NAMES;
  static GET_TASK_NAMES = environment.AUTH_SERVICE.ROLE.GET_TASK_NAMES;
  static LOAD_ALL_USERS_FOR_SELECTORS = environment.AUTH_SERVICE.USER.GET_USERS_FOR_SELECTOR;

  static  AUTH_SYSTEM_USER_ADD=environment.AUTH_SERVICE.SYSTEM_USER.ADD_USER;
  static  AUTH_SYSTEM_USER_GET_ALL=environment.AUTH_SERVICE.SYSTEM_USER.GET_ALL_USERS;
  static  AUTH_SYSTEM_USER_GET_BY_ID=environment.AUTH_SERVICE.SYSTEM_USER.GET_USER_BY_ID;
  static  AUTH_SYSTEM_USER_DELETE_BY_ID=environment.AUTH_SERVICE.SYSTEM_USER.DELETE_USER_BY_ID;

  static PAY_NET = environment.CORE_SERVICE.COMMON.PAYMENT_NETWORKS;

  static LOAD_FIELD_CONFIGURATION = environment.CORE_SERVICE.FIELD.LOAD_FIELD_CONFIGURATION_TABLE;
  static LOAD_FIELD_CONFIGURATOR = environment.CORE_SERVICE.FIELD.LOAD_FIELD_CONFIGURATOR;
  static LOAD_FIELD_CONFIGURATION_BY_STATUS = environment.CORE_SERVICE.FIELD.LOAD_FIELD_CONFIGURATION_By_STATUS;
  static SAVE_FIELD_CONFIGURATION = environment.CORE_SERVICE.FIELD.SAVE_FIELD_CONFIGURATION;
  static DELETE_FIELD_DEPENDENCIES = environment.CORE_SERVICE.FIELD.DELETE_FIELD_DEPENDENCIES;
  static DELETE_EFMS_ELEMENT = environment.CORE_SERVICE.FIELD.DELETE_EFMS_ELEMENT;

  static RULE_GROUP_SAVE = environment.CORE_SERVICE.RULE_GROUP.SAVE;
  static RULE_GROUP_UPDATE = environment.CORE_SERVICE.RULE_GROUP.UPDATE;
  static RULE_GROUP_GET_BY_ID = environment.CORE_SERVICE.RULE_GROUP.GET_BY_ID;
  static RULE_GROUP_FILTER = environment.CORE_SERVICE.RULE_GROUP.FILTER;
  static RULE_GROUP_TEST = environment.CORE_SERVICE.RULE_GROUP.TEST;

  static RULE_SAVE = environment.CORE_SERVICE.RULE.SAVE;
  static RULE_UPDATE = environment.CORE_SERVICE.RULE.UPDATE;
  static RULE_GET_BY_ID = environment.CORE_SERVICE.RULE.GET_BY_ID;
  static RULE_FILTER = environment.CORE_SERVICE.RULE.FILTER;
  static RULE_TEST = environment.CORE_SERVICE.RULE.TEST;

  static HIGH_RISK_GET_ALL = environment.CORE_SERVICE.HIGH_RISK.GET_ALL;
  static HIGH_RISK_GET_ALL_STREAM = environment.CORE_SERVICE.HIGH_RISK.GET_ALL_STREAM;
  static HIGH_RISK_GET_VARIABLE_NAMES = environment.CORE_SERVICE.HIGH_RISK.GET_VARIABLE_NAME;

  static VALIDATE_TRANSACTION_GET_ALL = environment.CORE_SERVICE.VALIDATE_TRANSACTION.GET_ALL;

  static PAYMENT_NETWORK_ADD_NEW_PAYMENT_NETWORK = environment.CORE_SERVICE.PAYMENT_NETWORKS.ADD_PAYMENT_NETWORK;
  static PAYMENT_NETWORK_LIST_PAYMENT_NETWORKS = environment.CORE_SERVICE.PAYMENT_NETWORKS.LIST_PAYMENT_NETWORKS;
  static PAYMENT_NETWORK_GET_PAYMENT_NETWORK_BY_ID = environment.CORE_SERVICE.PAYMENT_NETWORKS.GET_PAYMENT_NETWORK_BY_ID;

  static LOAD_REACTION_TEMPLATE_TABLE = environment.CORE_SERVICE.REACTION_TEMPLATE.LOAD_REACTION_TEMPLATE_TABLE;
  static LOAD_ALL_REACTION_TEMPLATE_TABLE = environment.CORE_SERVICE.REACTION_TEMPLATE.LOAD_ALL_REACTION_TEMPLATE_TABLE;
  static LOAD_REACTION_TEMPLATE_BY_ID = environment.CORE_SERVICE.REACTION_TEMPLATE.LOAD_REACTION_TEMPLATE_BY_ID;
  static DELETE_REACTION_TEMPLATE_BY_ID = environment.CORE_SERVICE.REACTION_TEMPLATE.DELETE_REACTION_TEMPLATE_BY_ID;
  static SAVE_REACTION_TEMPLATE = environment.CORE_SERVICE.REACTION_TEMPLATE.SAVE_REACTION_TEMPLATE;

  static SAVE_TEST_TRANSACTION=environment.CORE_SERVICE.RULE_TESTING_VALIDATION.ADD_TEST_TRANSACTION;


  static LOAD_ALL_DUAL_AUTH_REQUESTS = environment.CORE_SERVICE.DUAL_AUTH.GET_ALL_REQUESTS;
  static APPROVE_DUAL_AUTH_REQUEST = environment.CORE_SERVICE.DUAL_AUTH.APPROVE_REQUEST;
  static REJECT_DUAL_AUTH_REQUEST = environment.CORE_SERVICE.DUAL_AUTH.REJECT_REQUEST;
  static LOAD_DUAL_AUTH_REQUEST_BY_IDENTIFIER = environment.CORE_SERVICE.DUAL_AUTH.GET_REQUEST_BY_IDENTIFIER;

  static SET_RULES_FOR_REAL_TIME = environment.CORE_SERVICE.RISK_REAL_TIME.SET_RULES;
}
